2022/04/19 16:47:43 [error] 659#659: *18432 open() "/etc/nginx/nginx/html/api/v1" failed (2: No such file or directory), client: 90.249.140.201, server: shatkon.tk, request: "GET /api/v1 HTTP/2.0", host: "shatkon.tk"
2022/04/19 16:47:44 [error] 659#659: *18432 open() "/etc/nginx/nginx/html/favicon.ico" failed (2: No such file or directory), client: 90.249.140.201, server: shatkon.tk, request: "GET /favicon.ico HTTP/2.0", host: "shatkon.tk", referrer: "https://shatkon.tk/api/v1"
2022/04/19 16:47:56 [error] 659#659: *18432 open() "/etc/nginx/nginx/html/api/v1/docs" failed (2: No such file or directory), client: 90.249.140.201, server: shatkon.tk, request: "GET /api/v1/docs HTTP/2.0", host: "shatkon.tk"
2022/04/19 16:48:12 [error] 659#659: *18432 open() "/etc/nginx/nginx/html/docs" failed (2: No such file or directory), client: 90.249.140.201, server: shatkon.tk, request: "GET /docs HTTP/2.0", host: "shatkon.tk"
2022/04/19 16:48:14 [error] 659#659: *18440 open() "/etc/nginx/nginx/html/docs" failed (2: No such file or directory), client: 213.104.143.68, server: shatkon.tk, request: "GET /docs HTTP/1.1", host: "shatkon.tk", referrer: "https://www.google.com/"
2022/04/19 16:48:14 [error] 659#659: *18432 open() "/etc/nginx/nginx/html/docs" failed (2: No such file or directory), client: 90.249.140.201, server: shatkon.tk, request: "GET /docs HTTP/2.0", host: "shatkon.tk"
2022/04/19 16:53:22 [warn] 701#701: *18529 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/5/15/0000000155 while reading upstream, client: 90.249.140.201, server: shatkon.tk, request: "GET /static/js/bundle.js HTTP/1.1", upstream: "http://192.168.64.5:5000/static/js/bundle.js", host: "shatkon.tk", referrer: "http://shatkon.tk/"
2022/04/19 16:53:58 [warn] 701#701: *18542 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/6/15/0000000156 while reading upstream, client: 90.249.140.201, server: shatkon.tk, request: "GET /static/js/bundle.js HTTP/1.1", upstream: "http://192.168.64.5:5000/static/js/bundle.js", host: "shatkon.tk", referrer: "http://shatkon.tk/"
2022/04/19 16:58:07 [warn] 739#739: *18645 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/7/15/0000000157 while reading upstream, client: 90.249.140.201, server: shatkon.tk, request: "GET /static/js/bundle.js HTTP/1.1", upstream: "http://192.168.64.5:5000/static/js/bundle.js", host: "shatkon.tk", referrer: "http://shatkon.tk/"
2022/04/19 16:58:16 [warn] 739#739: *18651 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/8/15/0000000158 while reading upstream, client: 90.249.140.201, server: shatkon.tk, request: "GET /static/js/bundle.js.map HTTP/1.1", upstream: "http://192.168.64.5:5000/static/js/bundle.js.map", host: "shatkon.tk"
2022/04/19 16:59:47 [warn] 739#739: *18667 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/9/15/0000000159 while reading upstream, client: 90.249.140.201, server: shatkon.tk, request: "GET /static/js/bundle.js HTTP/2.0", upstream: "http://192.168.64.5:5000/static/js/bundle.js", host: "shatkon.tk", referrer: "https://shatkon.tk/"
2022/04/19 17:07:24 [error] 308#308: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "GET / HTTP/1.1", upstream: "http://192.168.64.5:5000/", host: "shatkon.tk"
2022/04/19 17:07:44 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/users/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/users/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:48 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/create/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/create/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:48 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:49 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/create/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/create/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:49 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:49 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/create/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/create/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:49 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:49 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/create/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/create/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:49 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:49 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/create/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/create/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:49 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:57 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/create/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/create/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:57 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:58 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/create/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/create/", host: "shatkon.tk", referrer: "http://localhost:90/"
2022/04/19 17:07:58 [error] 308#308: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 141.147.79.218, server: shatkon.tk, request: "OPTIONS /api/v1/urls/ HTTP/1.1", upstream: "http://192.168.64.1:8005/api/v1/urls/", host: "shatkon.tk", referrer: "http://localhost:90/"
